### ISSUE TITLE
out_of_range stoi

### ISSUE THREAD

**Issue by caballa** [dreal/dreal4#108]
I get this error message `libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: stoi: out of range`

with command

`dreal test.001.dreal.smt2`

I think the problem is while parsing these numbers `3333333333333333` and `10000000000000000`. Using the C++ API it looks OK

I zipped the smt2 file [here](https://github.com/dreal/dreal4/files/2535670/test.zip)

**Comment by soonho-tri** [comment]
This happens because a 32-bit integer can't hold this value `3333333333333333`. If you change it to ` 3333333333333333.0`, the parsing phase should be passed. (but I've found that it caused another problem which I'll address in another issue).

Please note that internally, we keep everything as an interval, `[double, double]`. We do not use an arbitrary-precision libraries such as MPFR. I'll do the followings:

1) Change the parsing code to use `64-bit` integer.
2) It will still raise an exception if a `64-bit` int value does not fit in `64-bit` double.

**Comment by soonho-tri** [comment]
Close by fce1be8f0b7e4a8c5543efbd12bfb1eeb2cea004
