### ISSUE TITLE
Does it handle symbolic matrix exponentials?

### ISSUE THREAD

**Issue by GDelimpa** [dreal/dreal4#141]
Lets say I have the following function:
H(x) = [1 0 0... 0]e^(A(x))*g(x) 
where A is n x n, g is 1 x n, so H is a scalar function. 
Is there some way that dreal can handle this, or should I do the matrix exponential calculation and the multiplications my self and then insert it to dreal?

**Comment by soonho-tri** [comment]
How do you use dReal? via its C++ API?

**Comment by GDelimpa** [comment]
I create an smt file, and call it via python using subprocess. It is like using it from the command line. The thing is that sympy seems that is very unreliable when it comes to a symbolic matrix exponential, which I think it shouldn't, since with the Cailey-Hamilton theorem it should be very easy to determine it.

**Comment by soonho-tri** [comment]
I have a plan to introduce Eigen to C++ API so that users can manipulate symbolic matrices. To do the same thing on the python side, I need to support numpy (or sympy) but it has a lower priority.

**Comment by GDelimpa** [comment]
Is there a chance that you render symbolic matrices handleable not just for the APIs, but also for us that use dreal basically from the command line and create smt files?

**Comment by soonho-tri** [comment]
My plan is:
1. Add [eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) support in C++ APIs.
2. Add [numpy](https://www.numpy.org/) support in Python so that users can create/manipulate numpy array/matrix of dReal's symbolic expressions.

After finishing up 1 and 2, we can talk about exposing the matrix support at the smt2 level.

So I say, we have a plan for it, but not a specific timeline yet.
