### ISSUE TITLE
Incorrect solution for a linear constraint problem

### ISSUE THREAD

**Issue by xrloong** [dreal/dreal4#154]
I used dreal to solve a linear constraint problem, but I found the solution is not correct.

The problem is:
```python
from dreal import Variable
from dreal import Minimize
from dreal import And
import dreal

innerLeft   = Variable("inner_left")
innerRight  = Variable("inner_right")
innerWidth  = Variable("in_width")
innerCenter = Variable("in_center")
outterLeft    = Variable("out_left")
outterRight   = Variable("out_right")
outterWidth   = Variable("out_width")
outterCenter = Variable("out_center")
constraints = And(
        innerLeft <= innerRight,
        (2 * innerCenter) == (innerLeft + innerRight),
        innerWidth == ( - innerLeft + innerRight),
        outterLeft <= outterRight,
        (2 * outterCenter) == (outterLeft + outterRight),
        outterWidth == ( - outterLeft + outterRight),
        outterLeft <= innerLeft,
        outterRight >= innerRight,

        outterCenter == innerCenter,

        outterLeft == 38,
        outterRight == 182,
        outterLeft >= 0,
        outterRight <= 255,
)
objective =  (outterWidth - innerWidth)

result = Minimize(objective, constraints, 0.0001)
answers = {}
for key, interval in result.items():
        answers[key] = interval.mid()
        print("{} = {}".format(key, interval.mid()))
print()
print("Objective:", objective.Evaluate(answers))
```

The solution given by dreal is:
```
inner_left = 110.0
inner_right = 110.0
in_width = -0.0
in_center = 110.0
out_left = 38.0
out_right = 182.0
out_width = 144.0
out_center = 110.0

Objective: 144.0
```

However, the correct solution should be:
```
inner_left = 38.0
inner_right = 182.0
in_width = 144.0
in_center = 110.0
out_left = 38.0
out_right = 182.0
out_width = 144.0
out_center = 110.0

Objective: 0.0
```

**Comment by soonho-tri** [comment]
Thanks for the report. I can reproduce the problem. I'll follow up in this issue if I have more findings.

**Comment by soonho-tri** [comment]
Hi @xrloong ,

What happens under the hood
----------------
This issue is caused by the use of equality constraints. In dReal, we rely on counterexamples in refining the current solution candidate. Forming a counterexample query, it delta-strengthens the input formula. For example, constraint `0 <= x` becomes `0.001 <= x` if it's strengthened by `0.001`. Now in case of equality constraints, say `0 == x`, the strengthened formula  is `0.001 <= x` and `x <= -0.001`. Note that this formula is unsatisfiable. As a consequence, the refinement loop in dReal terminates prematurely and it leads us to a premature solution (`144` instead of `0`) in this case.

What can I do?
-----------------

One thing you can do is to relax the original problem. See https://github.com/dreal/dreal4/blob/master/dreal/test/python/github_issue_154.py#L56-L82. The idea is to turn an equality constraint `0 == expr` into `-eps <= expr <= +eps`. You can pick an `eps` as long as it's bigger than the `precision` that you use in dReal. For example, in `github_issue_154.py`, we have:
```python
            # outterCenter == innerCenter,
            -eps <= innerCenter - outterCenter,
            innerCenter - outterCenter <= eps,
```
With this modification, dReal finds a solution, `0.0020664713138103252` which is close to the known minimum `0.0`.

Our plan
--------

We plan to add an option to automatically relax equality constraints in input files. Please subscribe https://github.com/dreal/dreal4/issues/122 if you want to get updates on this matter.
