### ISSUE TITLE
Is there a way to build python 3.x bindings? 

### ISSUE THREAD

**Issue by rohit507** [dreal/dreal4#69]
I'd like to use dReal for a project, and the rest of our toolkit is in python3.6. I'm not incredibly familiar with the python ecosystem, so forgive me if I'm missing some easy way to translate.

**Comment by soonho-tri** [comment]
We do not support it yet. But there is a way to build one by yourself.

1. Please follow https://github.com/dreal/dreal4/blob/master/README.md#how-to-build-dreal and check if you can build dReal4.

2. Apply the following patches (change a line in two files):

```diff
--- a/dreal/symbolic/__init__.py
+++ b/dreal/symbolic/__init__.py
@@ -1,4 +1,5 @@
 from dreal.symbolic._symbolic_py import *
+from functools import reduce

 # Explicitly import private symbols
 from dreal.symbolic._symbolic_py import __logical_and, __logical_or
--- a/dreal/workspace.bzl
+++ b/dreal/workspace.bzl
@@ -24,7 +24,7 @@ def dreal_workspace():
     )
     pkg_config_repository(
         name = "python2",
-        modname = "python2",
+        modname = "python3",
         pkg_config_paths = [
             "/usr/local/opt/python@2/lib/pkgconfig",
         ]
```

3. Execute `bazel test //dreal:api_test_py`. It will fail but generate the bindings anyway.

4. Execute `cd bazel-bin/dreal/api/api_test_py.runfiles/dreal` and `python3`. Enter the following program to check it works.

```python
from dreal.symbolic import Variable, logical_and, sin, cos
from dreal.api import CheckSatisfiability, Minimize

x = Variable("x")
y = Variable("y")
z = Variable("z")

f_sat = logical_and(0 <= x, x <= 10,
					0 <= y, y <= 10,
					0 <= z, z <= 10,
					sin(x) + cos(y) == z)

result = CheckSatisfiability(f_sat, 0.001)
print(result)
```

5. Copy the files under `bazel-bin/dreal/api/api_test_py.runfiles/dreal` into your `PYTHONPATH`. This should make you call dReal from your python3.

**Comment by soonho-tri** [comment]
I've updated the instructions. Please take a look.

**Comment by soonho-tri** [comment]
In case you're using Anaconda + Python3.6 on Ubuntu-16.04, please download [dreal4.18.05.2_anaconda_python3.6.tar.gz](https://github.com/dreal/dreal4/files/2027625/dreal4.18.05.2_anaconda_python3.6.tar.gz) and run:

```bash
cd ~/anaconda3/lib
tar xvf dreal4.18.05.2_anaconda_python3.6.tar.gz
```

**Comment by rohit507** [comment]
It's likely going to be a few days until I can check, but I'll give it a try when I can.

**Comment by soonho-tri** [comment]
@rohit507 , Thank you. Just FYI, there is another person who will test it in a day.

Also, I plan to work on #86 soon. Thanks for the patience!

**Comment by jsreid13** [comment]
I'm also looking to use dReal4 with python3 on Ubuntu 16.04, when you say
```diff
- a/tools/pybind11.BUILD
+ b/tools/pybind11.BUILD
``` 
do you mean that we should copy the entire repo to a new folder with a different name and build it there?

**Comment by soonho-tri** [comment]
@jsreid13 , you can open `tools/pybind11.BUILD` using an editor and change the line 32.

**Comment by jsreid13** [comment]
Thank you! I just got it to build and import successfully into Python 3.5, however when I try to run it in 3.6 python gives a version mismatch error saying that the module was compiled for version 3.5 (I changed the symlink for python3 and python3m to point to python3.6 and python3.6m respectively, but it still is having this issue when building. This could just be a local issue on my machine, but I'm open to any other recommendations you have for how to force Bazel to build for Python 3.6 instead of 3.5). I also tried putting the files in that tar.gz into my repo to see if that would help, I replaced ./opt/dreal/4.18.05.2/lib/python2.7/site-packages and ./opt/dreal/4.18.05.2/lib/libdreal.so with the provided files but now importing within python3.6 gives the error 
```
File "path_to_repo/dreal4/opt/dreal/4.18.05.2/lib/python2.7/site-packages/dreal/symbolic/__init__.py", line 1, in <module>
    from dreal.symbolic._dreal_symbolic_py import * 
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory```

Also I found out while doing an upgrade from python 3.5 to 3.6 that building dReal has python-apt as a dependency of installing python-dev that causes an error when building if you don't have it installed, I'll create a PR to add python-apt to all ubuntu install_prereqs.sh

**Comment by rohit507** [comment]
@jsreid13: I use [Vagrant](vagrantup.com) to set up a container with DReal and python 3.6. I've put the build scripts involved in [this Gist](https://gist.github.com/rohit507/d773987184129a08264dc95d29af8cf8). They should be pretty readable as is, and should work out of the box as long as you set up your project directory like this: 

```
<project-root>
├── ...
├── setup
│   ├── init.sh
│   ├── pybind11.patch
│   └── workspace.patch
└── Vagrantfile
```

If you're trying to read the Vagrantfile, the blocks starting with `config.vm.provision "shell", inline: <<-SHELL` are the scripts that are run as the system is provisioned. Those scripts assume the user is `vagrant` and that `<project-root>` is mounted to `/vagrant`. (Vagrant will map your project directory to `/vagrant` in the VM/container it's setting up.)

Hope that helps.

**Comment by soonho-tri** [comment]
@jsreid13 , I've added `@python-3.5` and `@python-3.6` instead of `@python3`. Please 1) check out the latest version of dReal, 2) Modify `tools/pybind11.BUILD` to use ` `@python-3.6`, 3) Run `bazel clean --expunge`, and 4) Rebuild dReal4. Let me know if you still have the issue.

**Comment by soonho-tri** [comment]
@jsreid13 and @rohit507 , our build script relies on the output from `pkg-config --cflags --libs python-3.5` (or `python-3.6`). If you have installed a python via `conda`, `pkg-config` fails to find it in the standard locations. If this is the case, please extend the `pkg_config_paths` in https://github.com/dreal/dreal4/blob/f488307240b06ee6133697a694a2eee2366248fb/dreal/workspace.bzl#L31-L46

**Comment by jsreid13** [comment]
I was just revisiting building this for my project and I found out what my issue was, I kept getting the following error: 
```
ERROR: ...path.../external/pybind11/BUILD.bazel:3:1: no such package '@python-3.6//': Unable to complete pkg-config setup for @python-3.6 repository: error 1 from [/usr/bin/pkg-config, "python-3.6"]:  and referenced by '@pybind11//:pybind11'
ERROR: Analysis of target '//:archive' failed; build aborted: Loading failed
```
The problem was when I installed python3.6 I didn't install python3.6-dev which was needed in Linux to create the .pc files for pkg_config which your last comment helped me find. Thanks for your help @soonho-tri and @rohit507 !

**Comment by soonho-tri** [comment]
Good to know that your issue is resolved now. I'll expand the Python section with additional information (i.e. required packages such as `python3.6-dev`.

**Comment by jsreid13** [comment]
One other thing I'm wondering about is that when I copy the export command you provide 
```
export PYTHONPATH=${PWD}/opt/dreal/4.18.03.2/lib/python2.7/site-packages:${PYTHONPATH}
```
It works, but the repo doesn't have a folder "4.18.03.2", only "4.18.05.2" (I'm guessing due to it being a newer version) so I'm wondering where this other path is located? Is it within one of the shared objects?

**Comment by soonho-tri** [comment]
@jsreid13, obviously the above instruction starting with `export PYTHONPATH=...` is outdated and one has to use the right version number (i.e. `4.18.05.2` in your case).

I'm wondering why it still works. What does `echo ${PYTHONPATH}` return in your terminal?

You need two things:

 - `PREFIX/lib/libdreal.so`
 - `PREFIX/lib/python{2.7|3.5|3.6}/site-packages/dreal/...`

and `PYTHONPATH` should include `PREFIX/lib/python{2.7|3.5|3.6}/site-packages` unless the above files are found in the standard location.

**Comment by jsreid13** [comment]
Just tested it an turns out it was only working because I tested importing dreal at the root of the repo so ``` import dreal ``` was actually importing the folder named dreal within this repo, not dreal in the site-packages though PYTHONPATH.

I got it working properly now by adding both the libdreal.so and site-packages to PYTHONPATH. For my project though I decided instead of having any future users build this repo and manually change their PYTHONPATH in order to use it I'd just cut these two locations out and put them directly into the package and use a setup,py script and change the import path within the __init__.py files to match and that is also working now. Thank you again for all the help!

**Comment by soonho-tri** [comment]
@jsreid13 , thanks for the comment. I think it'd be ideal if a user can use both of Python2 and Python3 bindings in a single Docker image. Do you think it's doable? If you can submit a PR, I'll be very happy to review it.

**Comment by jsreid13** [comment]
Good point, are you able to do that currently on your Linux system? I just started learning Docker this week but since it seems to have a full version of Linux inside of each container it should be able to do that if so. I think one option is to extract the tar file created by Bazel for the Python3 build to a different folder and then put both locations in PYTHONPATH, also [looking online](https://stackoverflow.com/questions/34066261/how-to-set-different-pythonpath-variables-for-python3-and-python2-respectively) I see that I can also create a setup.py file that can hold both opt/dreal/4.18.07.1/lib locations that could also work and be a bit tidier instead of having to change environment variables.

**Comment by soonho-tri** [comment]
I think this should be possible.

https://github.com/dreal/dreal4/blob/e11c5442a93c75fdf2a5b698838dd48fb56269bc/Dockerfile#L1-L13

In the current `Dockerfile`, I copy the dReal files to the `/usr` directly. For example, `opt/dreal/4.18.07.1/lib/*` goes to `/usr/lib/*`. In this way, a user of this container does not need to set up anything.

I think all we need to do is to append a few lines to the existing `Dockerfile` 1) to build bindings for Python3.5 and 2) copy `./opt/dreal/4.18.xx.x/lib/python3.5/site-packages/dreal` to `/usr/lib/python3.5/site-packages/dreal`. Do you think it's going to work?

**Comment by jsreid13** [comment]
You could put both `opt/dreal/4.18.07.1/lib/*` folders in two different locations, for example lib and lib3 since I believe the `lib/libdreal.so` file is different for the Python2 and Python3 versions. Then it would be up to the user to provide the correct PYTHONPATH after -e when running the container depending on if they want Python2 or 3, since providing both paths within PYTHONPATH wouldn't work. 
That is unless we renamed one of the `lib/python3.5/site-packages/dreal` folders to `lib/python3.5/site-packages/dreal3` so when importing for Python3 the command would be from `dreal3.symbolic import Variable, logical_and, sin, cos` but I feel like that is too messy since it requires changing imports within scripts.

**Comment by soonho-tri** [comment]
I came up with the following `Dockerfile`:

```Dockerfile
FROM       ubuntu:16.04
MAINTAINER soonho.kong@gmail.com

RUN mkdir /dreal4
COPY . /dreal4

# Extract version and save it at /DREAL_VERSION.
RUN cd /dreal4 \
    && echo `grep "DREAL_VERSION = " tools/dreal.bzl | cut -d '"' -f 2` > /DREAL_VERSION

# Install prerequsites.
RUN apt-get update && yes "Y" \
      | /dreal4/setup/ubuntu/16.04/install_prereqs.sh \
      && rm -rf /var/lib/apt/lists/* \
      && apt-get clean all

# Build dReal4 and install under /usr. Note that this installs
# bindings for python2.7 under /usr/lib/python2.7/dist-packages/.
RUN cd /dreal4 \
      && sed -i "s/lib\/python2.7\/site-packages/lib\/python2.7\/dist-packages/" `find dreal -name "BUILD.bazel"` \
      && bazel build //:archive \
      && tar xfz bazel-bin/archive.tar.gz \
      && cp -r opt/dreal/`cat /DREAL_VERSION`/* /usr

# Install python3.5, build bindings for python3.5 and install it under
# /usr/local/lib/python3.5/dist-packages.
RUN apt-get update && apt-get install -y libpython3.5-dev
RUN cd /dreal4 \
      && sed -i "s/python2/python-3.5/" tools/pybind11.BUILD.bazel \
      && sed -i "s/lib\/python2.7/lib\/python3.5/" `find dreal -name "BUILD.bazel"` \
      && bazel build //:archive \
      && tar xfz bazel-bin/archive.tar.gz \
      && cp -r opt/dreal/`cat /DREAL_VERSION`/lib/python3.5/dist-packages/dreal /usr/local/lib/python3.5/dist-packages/ \
      && rm -rf opt/ \
      && bazel clean --expunge
```

It installs bindings for python2.7 and python3.5 at `/usr/lib/python2.7/dist-packages` and `/usr/local/lib/python3.5/dist-packages`. They share the same `/usr/lib/libdreal.so`. It works for me on my machine. Can you check it on your side?

**Comment by jsreid13** [comment]
I just built this image and dReal works on both Python 2 and 3 within the container! Good idea to add the removal of dreal4/opt and cleaning bazel to help reduce the container size. However, this image is still quite a bit larger than the base dReal image (307MB vs 1.21GB), although it's not a priority I was reading online that the image size can be reduced if we use a lighter Ubuntu image like Debian Jessie or even Alpine, however when I try to use these it returns an error because the libibex-dev file on your PPA server doesn't support those versions of Linux. Is it difficult to allow these versions of Linux to download from the dReal PPA server?

**Comment by soonho-tri** [comment]
1) I've updated the Dockerfile above.
2) Now, it produces an image whose size is around 1.15GB. As you can see below (from `docker history`), 877MB of it is from the dependencies. I think it's not so meaningful to use different base containers.

```
IMAGE               CREATED              CREATED BY                                      SIZE                COMMENT
77f671953989        4 seconds ago        /bin/sh -c cd /dreal4       && sed -i "s/pyt…   2.9MB
3f7fd617be95        About a minute ago   /bin/sh -c cd /dreal4       && sed -i "s/lib…   137MB
d39fa9837f79        2 minutes ago        /bin/sh -c apt-get update && yes "Y"       |…   877MB
3e49a3d575ff        3 minutes ago        /bin/sh -c cd /dreal4     && echo `grep "DRE…   10B
44d83ab5d71f        3 minutes ago        /bin/sh -c #(nop) COPY dir:cf7fb213677c70480…   18.7MB
afc8b0ba608d        3 weeks ago          /bin/sh -c mkdir /dreal4                        0B
945313799f53        3 weeks ago          /bin/sh -c #(nop)  MAINTAINER soonho.kong@gm…   0B
0b1edfbffd27        3 months ago         /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B
<missing>           3 months ago         /bin/sh -c mkdir -p /run/systemd && echo 'do…   7B
<missing>           3 months ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$…   2.76kB
<missing>           3 months ago         /bin/sh -c rm -rf /var/lib/apt/lists/*          0B
<missing>           3 months ago         /bin/sh -c set -xe   && echo '#!/bin/sh' > /…   745B
<missing>           3 months ago         /bin/sh -c #(nop) ADD file:592c2540de1c70763…   113MB
```
